utils.responseEnvelopeContainsError: Add some test coverage
Make permanent some of the existing quirks of how this method is used
in practice.

Bug: T300067
Bug: T322779
Change-Id: I9b60af8e279c22f0f510cdd42018ccd10cf26f40